try

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,6 +34,18 @@ jobs:
           key: gradle-${{ matrix.minecraft }}
       - name: Make gradle wrapper executable
         run: chmod +x ./gradlew
+      - name: Update serial number
+        if: ${{ !startsWith(github.event.head_commit.message, 'rel') }}
+        run: |
+          if grep -q "mod_version[[:space:]]*=" gradle.properties; then
+            sed -i "s/^$[[:space:]]*mod_version[[:space:]]*=[[:space:]]*$$.*$$/\1\2-$RUN_NUMBER/" gradle.properties
+            echo "Updated gradle.properties:"
+            cat gradle.properties
+          else
+            echo "Error: mod_version not found in gradle.properties"
+            exit 1
+          fi
+
       - name: Build ${{ matrix.minecraft }}
         run: ./gradlew clean setupLibrary build -PbuildVersion="${{ matrix.minecraft }}" --no-daemon
 
